### ISSUE TITLE
checklist publish version 6.0

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#163]
- [x] 1. **Merge to *develop*** - Merge all branches with the changes that should be included in the new version first to the `develop` branch. @kbjarkefur 
- [x] 2. **Test in different operative systems** - This step is not necessary every time, but testing the commands in Stata on each of the PC, Mac and Linux operative systems should be done from time to time. A particularly good time to do this is after writing or editing code that depends on file paths, the console, special settings etc.
- [x] 3. **Update version and date** - In the `develop` branch, update the version number and date in all ado-files and all dates in all help files. See section below for details. @kbjarkefur 
- [x] 4. **Update version locals in ietoolkit** - In the _ietoolkit.ado_ file, update the _version_ and _versionDate_ locals at the top of the file. @kbjarkefur 
- [x] 5. **Create pull request from *develop* to *master*** - Create a pull request from the `develop` branch to the `master` branch, but do not merge it yet. We only want to merge after the content is published on SSC. The reason why we still want to create the pull request at this point is that any merge conflicts require us to make edits to the code we are sumbitting to SSC.
- [x] 6. **Make sure that there is no conflicts in the pull request you just created** - Make sure to include any edits this step requires you to do in the version you are sending to SSC. Do not merge yet.
- [x] 7. **Copy files to archive folder** - Make a folder with named after the new version number in the archive folder Dropbox\DIME Analytics\Data Coordinator\ietoolkit\ietoolkit archive\ and copy all ado-files and help files for all *ietoolkit* commands there.
- [x] 8. **Create a .zip file** - Create a .zip file with all ado-files and help files in the folder you just created in the archive folder. Then remove all files but the .zip file from the archive folder.
- [x] 9. **Email Prof. Baum** - Email the .zip file to **kit.baum@bc.edu**. If any commands are added or deleted, make note of that in the email.
- [x] 10. **Draft release note** - Go to the [release notes](https://github.com/worldbank/ietoolkit/releases) and draft a new release note for the new version. Follow the format from previous releases with links to [issues](https://github.com/worldbank/ietoolkit/issues) solved.
- [x] 11. **Wait for publication confirmation** - Do not proceed pass this step until Prof. Baum has confirmed that the new version is uploaded to the servers.
- [x] 12. **Merge the pull request** - Merge the pull request for this new version. It should not have any conflicts, so just merge it. Remeber to delete the *develop* branch and create a new *develop* branch from the most recent version of the *master* branch.
- [x] 13. **Publish release note** - Once the new version is up on SSC, publish the release note.
- [x] 14. **Close issues** - When the new version is up, close all the [issues](https://github.com/worldbank/ietoolkit/issues) that was solved in the new version.
- [x] 15. **Send announce email** - If it is a major release (new commands or significant updates to existing commands), send an email to DIME Team to announce the new version.

**Comment by kbjarkefur** [comment]
@luizaandrade , @bbdaniels , @mrimal 

Publication phase started! Do not start anything major in the develop or master branch before the publication process is over! Use other branches!

@luizaandrade , I think the amount of edits and an addition of a new command warrants v6.0 instead of v5.6

**Comment by LeonardoViotti** [comment]
The helpfile for ieddtab needs to be updated from time#treatment to time treatment time*treatment

**Comment by kbjarkefur** [comment]
Checklist completed!
