### ISSUE TITLE
Command review checklist

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#207]
# Organization
- [ ] Are the sections clear?
- [ ]  Is the code well documented?
- [ ] Could modularization improve code readability?
